### ISSUE TITLE
Could you release the pre-trained models?

### ISSUE THREAD

**Issue by manfred-git** [sjmoran/SIDGAN#1]
Thank you so much for releasing the code of this fascinating work! 
Is there any chance you could also release the pre-trained models?

**Comment by learning2hash** [comment]
Thank you for your interest in our work! Please contact Danai Triantafyllidou <danai.triantafyllidou@huawei.com> with this query.

**Comment by sjmoran** [comment]
Thank you for your interest in our work! Please contact Danai Triantafyllidou danai.triantafyllidou@huawei.com with this query.
