### ISSUE TITLE
How to train SIDGAN?

### ISSUE THREAD

**Issue by McFly-Jia** [sjmoran/SIDGAN#2]
I have read your paper "Low Light Video Enhancement using SyntheticData Produced with an Intermediate Domain Mapping'' and downloaded the code of the model from Github. But I notice that the hyperparameter settings in the code are inconsistent with the paper.I want to train the SIDGAN model from scratch, but I don't know how to use Vimeo-90k dataset to translate real-world videos into the low-light sensor specific domain. It is mentioned in the paper that you randomly select 400 Vimeo-90K videos to train the model. But your code trains all videos of Vimeo-90k. And we know the Vimeo-90k dataset has 91, 701 septuplet samples. If you randomly select 400 videos for training the model, shouldn't there be 91301 videos left to get the synthesized videos? However, It is mentioned in the paper that you finally generate 9, 366 synthetic videos, so I want to know how to use Vimeo-90k dataset to generate 9, 366 synthetic videos？Can you release a version of the code that is consistent with the hyperparameters in the paper? And can you tell me the detailed data you use?
Hope you can answer my questions and reply to me, I will thank you very much!

**Comment by sjmoran** [comment]
Thank you for your interest in our work! Please contact the first author Danai Triantafyllidou danai.triantafyllidou@huawei.com with this query.

**Comment by McFly-Jia** [comment]
Thank you for your reply. Can you answer some questions you know?
